### PR TITLE
forEach, getRow, getColumn, README updates!

### PR DESCRIPTION
**Pull request by possibly**
Hey again!

I have been working on a quick game that uses your fixed-2d-array, so as I make additional features that I need I go ahead and push them back to you. If this starts to add features you don't want in this module, let me know. I'll try and only add features I think are generally useful to anyone looking for a fixed 2d array.

npm run jshint

```
> fixed-2d-array@1.0.2 jshint /Users/tbro/dev/fixed-2d-array
> jshint test/* lib/*
```

npm run test-coveralls

```
> fixed-2d-array@1.0.2 test-coveralls /Users/tbro/dev/fixed-2d-array
> istanbul cover test/test.js  && cat ./coverage/lcov.info | coveralls && rm -rf ./coverage

TAP version 13
# Default values
ok 1 should be equal
ok 2 should be equal
# getHeight and getWidth
ok 3 should be equal
ok 4 should be equal
# get and set
ok 5 should be equal
# get correct row and column
ok 6 should be equal
ok 7 should be equal
ok 8 should be equal
ok 9 should be equal
ok 10 should throw
ok 11 should throw
# forEach
ok 12 should be equal
# exception on index out of bounds
ok 13 should throw
ok 14 should throw
ok 15 should throw
# get correct number of neighbours
ok 16 should be equal
ok 17 should be equal
ok 18 should be equal
ok 19 should be equal
ok 20 should be equal
ok 21 should be equal
ok 22 should be equal
=============================================================================
Writing coverage object [/Users/tbro/dev/fixed-2d-array/coverage/coverage.json]
Writing coverage reports at [/Users/tbro/dev/fixed-2d-array/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 100% ( 54/54 )
Branches     : 100% ( 14/14 )
Functions    : 100% ( 10/10 )
Lines        : 100% ( 53/53 )
================================================================================

1..22
# tests 22
# pass  22

# ok
```

### CODE REVIEW

**Comment by tillarnold** [comment]
Thanks a lot! I merged your PR.

**Comment by possibly** [comment]
No problem. Thanks for being so responsive.

Btw, is it rude to ask to be added to the npm registry as a collaborator
next time you update the registry? I haven't been a collaborator or module
owner before, so I am not sure if becoming a collaborator would give me
permissions over the files you don't want me to have.

Sincerely,

Tyler Brothers

   -

**Comment by tillarnold** [comment]
> Btw, is it rude to ask to be added to the npm registry as a collaborator
> next time you update the registry?

I don't know a lot about npm, so I don't really know how to add you as a collaborator. Is there a field in the package.json or a cli command for this?

**Comment by possibly** [comment]
Hmm...Not sure. I googled and found this: https://docs.npmjs.com/cli/owner.
My name on npm is `possiblylethal`.

Try typing "npm owner add possiblylethal fixed-2d-array" ?

Sincerely,

Tyler Brothers

   -

**Comment by tillarnold** [comment]
Oh I found this as well, but I wasn't sure if owner is the same as collaborator. I added you as owner.

**Comment by possibly** [comment]
Ah, I am not either. Thanks anyhow though!

Sincerely,

Tyler Brothers

   -

**Pull request merged**
